blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap

from .views import *
from .sitemap import sitemaps

urlpatterns = [
    path('', home, name="home"),
    path('blogs', blogs_view, name="blogs"),
    path('post/<slug:slug>', post_view, name="post"),
    path('category/<slug:slug>', category, name="category"),
    path('tag/<slug:slug>', tag, name="tag"),
    # path('add_comment/<int:post_id>', add_comment, name="add_comment"),
    path('add-reply/<int:comment_id>', add_reply, name="add_reply"),
    path('like-post/<int:post_id>', like_post, name="like-post"),
    path('search', search, name="search"),
    path('user/<slug:slug>', author_profile, name="author"),
    path('follow/<int:user_id>', follow, name="follow"),
    path('profile', profile, name="profile"),
    path('my-blogs', my_blogs_view, name="my_blogs"),
    path('add-post', add_post_view, name="add_post"),
    path('edit/<slug:slug>', edit_post_view, name="edit_post"),
    path('delete/<slug:slug>', delete_post, name="delete_post"),
    path('about', about_us, name="about"),
    path('all-notifications', all_notifications, name="all_notifications"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
]

handler404 = "blog.views.not_found"

insights/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Insights'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("", include("user_profile.urls")),
    path("notification/", include("notification.urls")),
]

handler404 = "blog.views.not_found"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path("open/<int:notification_id>", notification_redirect, name="open_notification"),
    path("seen", notifications_seen, name="notifications_seen")
]

blog/models.py
from django.db import models
from django.contrib import admin
from django.utils.text import slugify
from user_profile.models import User
from django.utils.html import format_html
from os import path

from utils import *

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=150)
    created_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True)

    @admin.display(description="Number")
    def blogs_number(self):
        return self.category_blogs.count()

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Tag(models.Model):
    title = models.CharField(max_length=150)
    created_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True)

    @admin.display(description="Number")
    def blogs_number(self):
        return self.tag_blogs.count()

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Blog(models.Model):
    title = models.CharField(
        max_length=250
    )

    content = models.TextField()

    banner = models.ImageField(
        upload_to="blog_banner"
    )

    author = models.ForeignKey(
        User,
        related_name='author_blogs',
        on_delete=models.CASCADE
    )

    category = models.ForeignKey(
        Category,
        related_name='category_blogs',
        on_delete=models.CASCADE
    )

    tags = models.ManyToManyField(
        Tag,
        related_name='tag_blogs',
        blank=True
    )

    like = models.ManyToManyField(
        User,
        # related_name="like_user",
        blank=True,
        through='Like'
    )

    created_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True, unique=True)

    @admin.display(description="Preview")
    def show_banner(self):
        return format_html('<img src="/%s" width="150" height="150" />' % (self.banner.url))
    
    def formatted_date(self):
        return datetime_format(self.created_date)
    
    def process_image(self):
        new_path = get_random_image_name(self.banner.path)
        resize_img(self.banner.path, new_path, 1200, 630)
        self.banner.name = path.join("blog_banner", path.split(new_path)[1])
    
    def generate_slug(self, title):
        self.slug = slugify(title)

        if Blog.objects.filter(slug=self.slug).exists():
            self.generate_slug(f"{self.title} {get_random_slug_suffix()}")

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.generate_slug(self.title)
            
        super().save(*args, **kwargs)
        if not check_image_size(self.banner.path, 1200, 630):
            self.process_image()
            super().save(*args, **kwargs)
    

class Comment(models.Model):
    text = models.TextField()

    user = models.ForeignKey(
        User,
        related_name="comment_user",
        on_delete=models.CASCADE
    )

    blog = models.ForeignKey(
        Blog,
        related_name="blog_comments",
        on_delete=models.CASCADE
    )

    created_date = models.DateTimeField(auto_now_add=True)

    def formatted_date(self):
        return datetime_format(self.created_date)


    # confirmed = models.BooleanField(default=True)

    def __str__(self):
        return self.text
    

class Reply(models.Model):
    text = models.TextField()

    user = models.ForeignKey(
        User,
        related_name="reply_user",
        on_delete=models.CASCADE
    )

    comment = models.ForeignKey(
        Comment,
        related_name="comment_reply",
        on_delete=models.CASCADE
    )

    created_date = models.DateTimeField(auto_now_add=True)

    def formatted_date(self):
        return datetime_format(self.created_date)


    # confirmed = models.BooleanField(default=True)

    def __str__(self):
        return self.text


class Like(models.Model):
    user = models.ForeignKey(
        User,
        # related_name="user_like",
        on_delete=models.CASCADE
    )

    blog = models.ForeignKey(
        Blog,
        related_name="blog_like",
        on_delete=models.CASCADE
    )

    created_date = models.DateTimeField(auto_now_add=True)

notification/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from user_profile.models import User
from utils import datetime_format

# Create your models here.
class Notification(models.Model):
    NOTIFICATION_TYPE = ("Blog", "Follow", "Like", "Comment", "Reply")

    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE
    )

    object_id = models.BigIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(
        User,
        related_name="user_notifications",
        on_delete=models.CASCADE
    )
    creator = models.ForeignKey(
        User,
        related_name="user_notifications_send",
        on_delete=models.CASCADE
    )

    is_seen = models.BooleanField(default=False)

    notification_type = models.CharField(
        max_length=20,
        choices=list(zip(NOTIFICATION_TYPE, NOTIFICATION_TYPE))
    )

    created_date = models.DateTimeField(auto_now_add=True)

    def text(self):
        if self.notification_type == "Follow":
            return f"{self.creator.username} started following you"
        
        elif self.notification_type == "Blog":
            return f"{self.creator.username} posted a new blog"
        
        elif self.notification_type == "Like":
            return f"{self.creator.username} liked your blog"
        
        elif self.notification_type == "Comment":
            return f"{self.creator.username} commented on your blog"
        
        elif self.notification_type == "Reply":
            return f"You have a new reply from {self.creator.username}"

    def formatted_date(self):
        return datetime_format(self.created_date)

    def __str__(self):
        return self.text()

user_profile/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from .managers import CustomUserManager

from utils import *

# Create your models here.
class User(AbstractUser):
    username = models.CharField(
        "username",
        max_length=150,
        unique=True,
        blank=True,
        null=True
    )
    
    email = models.EmailField(
        "email address",
        unique=True
    )

    profile_image = models.ImageField(
        null=True,
        blank=True,
        upload_to="profile_image",
        default="./profile_image/man.png"
    )

    followers = models.ManyToManyField("Follow")

    slug = models.SlugField(blank=True, unique=True)

    REQUIRED_FIELDS = ["email"]

    objects = CustomUserManager()

    def __str__(self):
        return self.username

    def process_image(self):
        new_path = get_random_image_name(self.profile_image.path)
        resize_img(self.profile_image.path, new_path, 400, 400)
        self.profile_image.name = path.join("profile_image", path.split(new_path)[1])

    def generate_slug(self, username):
        self.slug = slugify(username)

        if User.objects.filter(slug=self.slug).exists():
            self.generate_slug(f"{self.username} {get_random_slug_suffix()}")
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.generate_slug(self.username)
        super().save(*args, **kwargs)
        
        if self.profile_image and not check_image_size(self.profile_image.path,400, 400):
            self.process_image()
            super().save(*args, **kwargs)

class Follow(models.Model):
    followed = models.ForeignKey(
        User,
        related_name="user_followers",
        on_delete=models.CASCADE
    )

    follower = models.ForeignKey(
        User,
        related_name="user_followed",
        on_delete=models.CASCADE
    )

    created_date = models.DateTimeField(auto_now_add=True)        
    

blog/forms.py
from django import forms
from .models import Blog, Tag
from django.utils.text import slugify
from tinymce.widgets import TinyMCE
from user_profile.models import User

class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={
        "rows": 6,
        "id": "message",
        "placeholder": "Type your comment",
    }), required=True, label=False)

class ReplyForm(forms.Form):
    reply = forms.CharField(widget=forms.Textarea(attrs={
        "rows": 3,
        "id": "message",
        "placeholder": "Type your reply",
    }), required=True, label=False)

class PersonalInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name")

        widgets = {
            # "username": forms.TextInput(attrs={
            #     "class": "form-control",
            #     "placeholder": "Enter your username (optional)"
            # }),
            "first_name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter your first name (optional)"
            }),
            "last_name": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter your last name (optional)"
            })
        }

    # def clean_username(self):
    #     if not (username := self.cleaned_data.get("username")):
    #         return None
        
    #     model = self.Meta.model
    #     user = model.objects.filter(username__iexact=username).exclude(pk=self.instance.pk)

    #     if user.exists():
    #         raise forms.ValidationError("A user with that name already exist")

    #     return username

class ChangePasswordForm(forms.ModelForm):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Enter your new password"
    }), required=True)

    conf_password = forms.CharField(widget=forms.PasswordInput(attrs={
        "class": "form-control",
        "placeholder": "Confirm your new password"
    }), required=True)
    
    class Meta:
        model = User
        fields = ["password"]
            
        widgets = {
            "password": forms.PasswordInput(attrs={
                "class": "form-control",
                "placeholder": "Enter your password"
            })
        }

    def clean_password(self):
        password = self.cleaned_data.get("password")

        if not self.instance.check_password(password):
            raise forms.ValidationError("Incorrect password")
        
        return password

    def clean(self):
        if self.is_valid():
            password = self.cleaned_data.get("new_password")
            password2 = self.cleaned_data.get("conf_password")
            if password != password2:
                raise forms.ValidationError("Passwords don't match")
            
        return self.cleaned_data


class ProfileImageForm(forms.Form):
    profile_image = forms.ImageField(required=True)


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ["title", "category", "content", "banner"]

        widgets = {
            "title": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Enter the post title"
            }),
            "category": forms.Select(attrs={
                "class": "form-control"
            }),
            "content": TinyMCE(attrs={
                "class": "form-control",
                "placeholder": "An awesome article..."
            }),
            "banner": forms.FileInput(attrs={
                "class": "form-control h-100"
            }),
            # "tags": forms.HiddenInput(),
        }

    # def clean_tags(self):
    #     print("Got")
    #     # tags_list = [tag.strip() for tag in self.cleaned_data.get("tags").split(",")]

    #     # for tag in tags_list:
    #     #     if tag != "" and (tag_input := Tag.objects.filter(slug=slugify(tag))):
    #     #         tag_input = Tag(title = tag)
    #     #         tag_input.save()

    #     return [tag.strip() for tag in self.cleaned_data.get("tags").split(",")]

notification/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpRequest, Http404, HttpResponseForbidden, JsonResponse
from django.contrib.auth.decorators import login_required
from .models import Notification

# Create your views here.
@login_required(login_url="/login")
def notification_redirect(request: HttpRequest, notification_id: int):
    if (notification := Notification.objects.get(pk=notification_id)):
        if request.user == notification.user:
            
            notification.is_seen = True
            notification.save()
            if notification.notification_type == "Follow":
                return redirect(reverse("profile"))
            
            elif notification.notification_type in ["Blog", "Like"]:
                return redirect(reverse("post", kwargs={"slug": notification.content_object.slug}))

            elif notification.notification_type == "Comment":
                return redirect(reverse("post", kwargs={"slug": notification.content_object.blog.slug})) 
            
            elif notification.notification_type == "Reply":
                return redirect(reverse("post", kwargs={"slug": notification.content_object.comment.blog.slug}))
            return redirect("/")
        else:
            return HttpResponseForbidden()
    else:
        return Http404()
    

@login_required(login_url="/login")
def notifications_seen(request: HttpRequest):
    for notification in Notification.objects.filter(user=request.user):
        notification.is_seen = True
        notification.save()

    return JsonResponse({
        "code": 200
    })

blog/templates/pages/add_post.html
{% extends "layout.html" %}

{% load static %}

{% block head %}

{{ form.media }}

{% endblock %}

{% block content %}

<section class="main-content">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" action="{% url 'add_post' %}" enctype="multipart/form-data" id="add-form">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                    {% endif %}

                    <div class="form-group">
                        <label for="id_title">Title: </label>
                        {{ form.title }}

                        {% if form.title.errors %}
                        <div class="text-danger">
                            {{ form.title.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_category">Category: </label>
                        {{ form.category }}

                        {% if form.category.errors %}
                        <div class="text-danger">
                            {{ form.category.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_content">Content: </label>
                        {{ form.content }}

                        {% if form.content.errors %}
                        <div class="text-danger">
                            {{ form.content.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_banner">Banner: </label>
                        {{ form.banner }}

                        {% if form.banner.errors %}
                        <div class="text-danger">
                            {{ form.banner.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="tags">Tags: </label>
                        <input id="id_tags" type="hidden" value="" name="tags" />

                        <input class="form-control" id="tags" type="text" value="" data-role="tagsinput"
                            placeholder="Add tags" />

                        {% if form.tags.errors %}
                        <div class="text-danger">
                            {{ form.tags.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <button type="submit" class="btn btn-sec" id="submit-btn">Post</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block scripts %}

<script src="{% static 'blog/js/tags-input.js' %}"></script>

{% endblock %}

blog/templates/pages/author.html
{% extends "layout.html" %}

{% load static %}

{% block content %}

<section class="main-content profile">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="text-center m-5 img-edit">
                    <img class="rounded rounded-circle w-100" src="{{ author.profile_image.url }}">
                </div>
                <hr>
                <div class="d-flex justify-content-center p-2">
                    Posts: {{ author.author_blogs.count }}
                </div>
                <div class="d-flex justify-content-center p-2">
                    Following:
                    {% if author.user_followed.count > 0 %}
                    {{ author.user_followed.count }}
                    {% else %}
                    0
                    {% endif %}
                </div>
                <div class="d-flex justify-content-center p-2">
                    Followers:
                    {% if author.user_followers.count > 0 %}
                    {{ author.user_followers.count }}
                    {% else %}
                    0
                    {% endif %}
                </div>
                <div class="d-flex justify-content-center p-2">
                    {% if user.is_authenticated %}
                    <form method="post" action="{% url 'follow' user_id=author.pk %}">
                        {% csrf_token %}
                        {% if following %}
                        <button type="submit" id="form-submit" class="btn btn-sec-outline">Following</button>
                        {% else %}
                        <button type="submit" id="form-submit" class="btn btn-sec">Follow</button>
                        {% endif %}
                    </form>
                    {% else %}
                    <a href="{% url 'login' %}" class="link link-primary">Login to follow</a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-8 p-3">
                {% include "components/messages.html" %}
                <h2>{{ author.username }}</h2>
                {% for blog in author.author_blogs.all %}
                <div class="blog-post">
                    <a href="{% url 'post' slug=blog.slug %}" class="d-flex ">
                        <div class="col-4">
                            <img class="w-100" src="{{ blog.banner.url }}">
                        </div>
                        <div class="col-8">
                            <h6>{{ blog.title }}</h6>
                            <p>
                                {{ blog.content | truncatewords:20 | striptags | escape }}
                            </p>
                        </div>
                    </a>
                </div>
                {% empty %}
                <div class="d-flex justify-content-center">
                    <p>This author has no posts</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/pages/edit_post.html
{% extends "layout.html" %}

{% load static %}

{% block head %}

{{ form.media }}

{% endblock %}

{% block content %}

<section class="main-content">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="post" action="{% url 'edit_post' slug=form.instance.slug %}" enctype="multipart/form-data"
                    id="add-form">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                    {% endif %}

                    <div class="form-group">
                        <label for="id_title">Title: </label>
                        {{ form.title }}

                        {% if form.title.errors %}
                        <div class="text-danger">
                            {{ form.title.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_category">Category: </label>
                        {{ form.category }}

                        {% if form.category.errors %}
                        <div class="text-danger">
                            {{ form.category.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_content">Content: </label>
                        {{ form.content }}

                        {% if form.content.errors %}
                        <div class="text-danger">
                            {{ form.content.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_banner">Banner: </label>
                        <img src="{{ form.instance.banner.url }}" class="w-100">
                        {{ form.banner }}

                        {% if form.banner.errors %}
                        <div class="text-danger">
                            {{ form.banner.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="tags">Tags: </label>
                        <input id="id_tags" type="hidden" value="" name="tags" />

                        <input class="form-control" id="tags" type="text" value="{{ post_tags }}" data-role="tagsinput"
                            placeholder="Add tags" />

                        {% if form.tags.errors %}
                        <div class="text-danger">
                            {{ form.tags.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <button type="submit" class="btn btn-sec" id="submit-btn">Save</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block scripts %}

<script src="{% static 'blog/js/tags-input.js' %}"></script>

{% endblock %}

blog/templates/pages/profile.html
{% extends "layout.html" %}

{% load static %}

{% block content %}

<section class="main-content profile">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="text-center m-5 img-edit">
                    <form class="img-form" action="{% url 'profile' %}?action=image" enctype="multipart/form-data"
                        method="post">
                        {% csrf_token %}

                        <img class="rounded rounded-circle w-100" src="{{ user.profile_image.url }}">
                        <label for="id_profile_image">
                            <div>
                                <i class="fa-regular fa-pen-to-square"></i>
                            </div>
                        </label>
                        {{ image_form.profile_image }}
                    </form>
                </div>
                <hr>
                <div class="row justify-content-around">
                    <div>
                        Following:
                        {% if user.user_followed.count > 0 %}
                        {{ user.user_followed.count }}
                        {% else %}
                        0
                        {% endif %}
                    </div>
                    <div>
                        Followers:
                        {% if user.user_followers.count > 0 %}
                        {{ user.user_followers.count }}
                        {% else %}
                        0
                        {% endif %}
                    </div>
                </div>
                <hr>
                <div class="d-flex flex-column">
                    <a class="btn btn-outline-secondary m-2" href="{% url 'my_blogs' %}">My blogs</a>
                    <a class="btn btn-outline-secondary m-2" href="{% url 'add_post' %}">Add blog</a>
                </div>
            </div>
            <div class="col-12 col-md-8 p-3">
                {% include "components/messages.html" %}
                <h2 class="mb-3">Personal info: </h2>
                <form action="{% url 'profile' %}?action=info" method="post">
                    {% csrf_token %}

                    {% if profile_form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ profile_form.non_field_errors }}
                    </div>
                    {% endif %}

                    <div class="form-group">
                        <label for="id_username">Username: </label>
                        <input type="text" class="form-control" , placeholder="Enter your username"
                            value="{{ user.username }}" disabled>
                    </div>

                    <div class="form-group">
                        <label for="id_email">Email address: </label>
                        <input type="email" class="form-control" , placeholder="Enter your email"
                            value="{{ user.email }}" disabled>
                    </div>

                    <div class="form-group">
                        <label for="id_first_name">First name: </label>
                        {{ profile_form.first_name }}

                        {% if profile_form.first_name.errors %}
                        <div class="text-danger">
                            {{ profile_form.first_name.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_last_name">Last name: </label>
                        {{ profile_form.last_name }}

                        {% if profile_form.last_name.errors %}
                        <div class="text-danger">
                            {{ profile_form.last_name.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <button type="submit" class="btn btn-sec">Save</button>
                </form>

                <hr>

                <h2 class="mb-3">Change password: </h2>
                <form action="{% url 'profile' %}?action=password" method="post">
                    {% csrf_token %}

                    {% if password_form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ password_form.non_field_errors }}
                    </div>
                    {% endif %}

                    <div class="form-group">
                        <label for="id_password">Current password: </label>
                        {{ password_form.password }}

                        {% if password_form.password.errors %}
                        <div class="text-danger">
                            {{ password_form.password.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_new_password">New password: </label>
                        {{ password_form.new_password }}

                        {% if password_form.new_password.errors %}
                        <div class="text-danger">
                            {{ password_form.new_password.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <div class="form-group">
                        <label for="id_conf_password">Confirm password: </label>
                        {{ password_form.conf_password }}

                        {% if password_form.conf_password.errors %}
                        <div class="text-danger">
                            {{ password_form.conf_password.errors }}
                        </div>
                        {% endif %}
                    </div>

                    <button type="submit" class="btn btn-sec">Save</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block scripts %}

<script src="{% static 'blog/js/profile-img.js' %}"></script>

{% endblock %}